on:
  push:
    tags:
      - "*"

jobs:
  publish-to-curseforge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build the modpack
        run: |
          make clean-all
          make server pack
          echo "modpackfile=$(ls _build/modpack/*.zip)" >> $GITHUB_ENV
          echo "serverfile=$(ls _build/server/*.zip)" >> $GITHUB_ENV
      - name: "Upload modpack to CurseForge"
        uses: itsmeow/curseforge-upload@v3
        with:
          file_path: "${{ env.modpackfile }}"
          game_endpoint: "minecraft"
          game_versions: "Minecraft 1.19.2"
          project_id: "${{ secrets.CF_PROJECT_ID }}"
          token: "${{ secrets.CF_API_TOKEN }}"
      - name: "Upload server pack to CurseForge"
        uses: itsmeow/curseforge-upload@v3
        with:
          file_path: "${{ env.serverfile }}"
          game_endpoint: "minecraft"
          game_versions: "Minecraft 1.19.2"
          project_id: "${{ secrets.CF_PROJECT_ID }}"
          token: "${{ secrets.CF_API_TOKEN }}"
